apiVersion: tekton.dev/v1beta1
kind: Task

metadata:
  name: check-vulnerabilities

spec:
  description: >-
    This is the task for checking if all the vulnerabilities are within limits; if not then break the build.
  workspaces:
    - name: report
      description: Volume of Workspace where all reports and dependencies are installed.
    
  # Task parameters take values from global parameters  
  params:
    - name: total-vulnerabilities
      description: Maximum number of vulnerabilities allowed.
      default: "3"

    - name: critical-vulnerabilities
      description: Maximum number of critical vulnerabilities allowed.
      default: "0"
    
    - name: high-vulnerabilities
      description: Maximum number of high vulnerabilities allowed.
      default: "0"
    
    - name: medium-vulnerabilities
      description: Maximum number of medium vulnerabilities allowed.
      default: "1"
    
    - name: low-vulnerabilities
      description: Maximum number of low vulnerabilities allowed.
      default: "2"
    
    - name: report-file-path
      description: Path of the file to save analysis report.
    
    - name: crda-image
      

  # Task definition
  steps:
    - name: check-vulnerabilities
      image: $(params.crda-image)
      workingDir: $(workspaces.report.path)
      script: |
        #!/bin/sh