apiVersion: tekton.dev/v1beta1
kind: Task

metadata:
  name: golang-setup-env

spec:
  description: >-
    This is the task for installing the packages depending on the ecosystem.
  workspaces:
    - name: report
      description: Volume of Workspace where all reports and dependencies are installed.
    
  # Task parameters take values from global parameters  
  params:
    - name: file-url
      description: URL of the manifest file.

    - name: manifest-file-path
      description: Path of the manifest file to perform analysis.

    - name: pkg-installation-directory-path
      description: Path of a directory in workspace, where dependencies will be installed.

    - name: golang-image
      description: Docker Golang Image.
      

  # Task definition
  steps:
    - name: golang-setup-env
      image: $(params.golang-image)
      workingDir: $(workspaces.report.path)
      script: |
        #!/bin/sh
        mkdir -p $(params.pkg-installation-directory-path)
        curl $(params.file-url) --output $(params.manifest-file-path)

        echo $(ls)
        mv $(params.manifest-file-path) ./$(params.pkg-installation-directory-path)
        cd $(params.pkg-installation-directory-path)

        go mod download

        cd ..
        mv ./$(params.pkg-installation-directory-path)/$(params.manifest-file-path) .
        echo $(ls)