apiVersion: tekton.dev/v1beta1
kind: Task

metadata:
  name: maven-setup-env

spec:
  description: >-
    This is the task for installing the packages of maven/Java ecosystem.
  workspaces:
    - name: report
      description: Volume of Workspace where all reports and dependencies are installed.
    
  # Task parameters take values from global parameters  
  params:
    - name: file-url
      description: URL of the manifest file

    - name: manifest-file-path
      description: Path of the manifest file to perform analysis.

    - name: pkg-installation-directory-path
      description: Path of a directory in workspace, where dependencies will be installed.

    - name: image
      description: Docker Maven Image.
      

  # Task definition
  steps:
    - name: maven-setup-env
      image: $(params.image)
      workingDir: $(workspaces.report.path)
      script: |
        #!/bin/sh

        mkdir -p $(params.pkg-installation-directory-path)
        curl $(params.file-url) --output $(params.manifest-file-path)
        echo $(ls)
        
        mv $(params.manifest-file-path) ./$(params.pkg-installation-directory-path)
        cd $(params.pkg-installation-directory-path)

        printf "Installing dependencies...\n"
        
        mvn install

        cd ..
        mv ./$(params.pkg-installation-directory-path)/$(params.manifest-file-path) .
        
        printf "Successfully installed dependencies\n"

