apiVersion: tekton.dev/v1beta1
kind: Task

metadata:
  name: setup-env

spec:
  description: >-
    This is the task for installing the packages depending on the ecosystem.
  workspaces:
    - name: report
      description: Volume of Workspace where all reports and dependencies are installed
    
  # Task parameters take values from global parameters  
  params:
    - name: file-url
      description: URL of the manifest file

    - name: manifest-file-path
      description: Path of the manifest file to perform analysis.

    - name: pkg-installation-directory-path
      description: Path of a directory in workspace, where dependencies will be installed.

    - name: image
      description: Image of the specific language which is used by CRDA to perform analysis
      

  # Task definition
  steps:
    - name: setup-env
      image: $(params.image)
      workingDir: $(workspaces.report.path)
      script: |
        #!/bin/sh
        mkdir -p $(params.pkg-installation-directory-path)
        curl $(params.file-url) --output $(params.manifest-file-path)

        printf "Installing dependencies...\n"
        pip3 install --target=$(params.pkg-installation-directory-path) \
        -r $(params.manifest-file-path) --upgrade

        printf "Successfully installed dependencies\n"
