# A Custom task given for demo purpose to download the manifest and install its dependencies.
apiVersion: tekton.dev/v1beta1
kind: Task

metadata:
  name: go-setup-env
spec:
  description: >-
    This is the task for installing the go packages.
  params:
    - name: file_url
    - name: manifest-file-path
      default: go.mod
    - name: pkg-installation-directory-path
      default: site-package
    - name: image
      default: 
  steps:
    - name: go-setup-env
      image: $(params.image)
      workingDir: $(workspaces.report.path)
      script: |
        #!/bin/sh
        mkdir -p $(params.pkg-installation-directory-path)
        curl $(params.file_url) --output $(params.manifest-file-path)
        mv go.mod ./$(params.pkg-installation-directory-path)
        cd $(params.pkg-installation-directory-path)
        go mod download
        cd ..
        mv ./$(params.pkg-installation-directory-path)/go.mod .
  workspaces:
    - name: report