apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: dependency-check-pipeline

spec:
  workspaces:
    - name: report

  params:
    - name: file-url

    - name: manifest-file-path

    - name: pkg-installation-directory-path
      default: dependency-directory

    - name: report-file-path
      default: crda-report.json
      
    - name: image

    - name: crda-image

  tasks:
    - name: setup-env
      taskRef:
        name: setup-env
      workspaces:
        - name: report
          workspace: report
      params:
        - name: file-url
          value: $(params.file-url)

        - name: pkg-installation-directory-path
          value: $(params.pkg-installation-directory-path)

        - name: manifest-file-path
          value: $(params.manifest-file-path)

        - name: image
          value: $(params.image)

    - name: python-crda-task
      taskRef:
        name: python-crda-task
      runAfter:
        - setup-env
      workspaces:
        - name: report
          workspace: report
      params:
        - name: pkg-installation-directory-path
          value: $(params.pkg-installation-directory-path)

        - name: manifest-file-path
          value: $(params.manifest-file-path)

        - name: image
          value: $(params.image)
          
        - name: report-file-path
          value: $(params.report-file-path)
