apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: dependency-check-pipeline

spec:
  workspaces:
    - name: output

  params:
    - name: repository

    - name: manifest-file-path

    - name: pkg-installation-directory-path
      default: dependency-directory

    - name: report-file-path
      default: crda-report.json
      
    - name: image

    - name: total-vulnerabilities

    - name: critical-vulnerabilities
    
    - name: high-vulnerabilities
    
    - name: medium-vulnerabilities
    
    - name: low-vulnerabilities

  tasks:
    - name: clone-git-repo
      workspaces:
      - name: output
        workspace: output
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repository)
        - name: deleteExisting
          value: "true"
    - name: npm-setup-env
      taskRef:
        name: npm-setup-env
      runAfter:
        - clone-git-repo
      workspaces:
        - name: output
          workspace: output
      params:

        - name: pkg-installation-directory-path
          value: $(params.pkg-installation-directory-path)

        - name: manifest-file-path
          value: $(params.manifest-file-path)

        - name: image
          value: $(params.image)

    - name: npm-crda-task
      taskRef:
        name: npm-crda-task
      runAfter:
        - npm-setup-env
      workspaces:
        - name: output
          workspace: output
      params:
        - name: pkg-installation-directory-path
          value: $(params.pkg-installation-directory-path)

        - name: manifest-file-path
          value: $(params.manifest-file-path)

        - name: image
          value: $(params.image)
          
        - name: report-file-path
          value: $(params.report-file-path)

    - name: check-vulnerabilities
      taskRef:
        name: check-vulnerabilities
      runAfter:
        - npm-crda-task
      workspaces:
        - name: output
          workspace: output
      params:   
        - name: total-vulnerabilities
          value: $(params.total-vulnerabilities)

        - name: critical-vulnerabilities
          value: $(params.critical-vulnerabilities)
        
        - name: high-vulnerabilities
          value: $(params.high-vulnerabilities)
        
        - name: medium-vulnerabilities
          value: $(params.medium-vulnerabilities)
        
        - name: low-vulnerabilities
          value: $(params.low-vulnerabilities)

        - name: report-file-path
          value: $(params.report-file-path)
        
        - name: image
          value: $(params.image)
