apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: dependency-check-pipeline-run
spec:
  pipelineRef:
    name: dependency-check-pipeline
  workspaces:
    - name: report
      persistentvolumeclaim:
        claimName: report

  params:
    - name: file_url
      value: https://raw.githubusercontent.com/khyatisoneji/Dock-K8s-Tkn/main/UI-GoServer/go.mod
    
    - name: language
      value: "1"

    - name: manifest-file-path
      value: go.mod

    - name: pkg-installation-directory-path
      value: dependency-directory

    - name: report-file-path
      value: crda-report.json

    - name: image
      value: quay.io/ksoneji/crda
