apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: dependency-check-pipeline-run
spec:
  pipelineRef:
    name: dependency-check-pipeline
  workspaces:
    - name: report
      persistentvolumeclaim:
        claimName: report

  params:
    - name: file-url
      value: https://raw.githubusercontent.com/khyatisoneji/dependency-check/requirements.txt

    - name: manifest-file-path
      value: requirements.txt

    - name: pkg-installation-directory-path
      value: dependency-directory

    - name: report-file-path
      value: crda-report.json

    - name: image
      value: quay.io/ksoneji/crda:python
