apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: dependency-check-pipeline-run
spec:
  pipelineRef:
    name: dependency-check-pipeline
  workspaces:
    - name: report
      persistentvolumeclaim:
        claimName: report

  params:
    - name: file-url
      value: https://raw.githubusercontent.com/khyatisoneji/Dock-K8s-Tkn/main/UI-GoServer/go.mod

    - name: manifest-file-path
      value: go.mod

    - name: pkg-installation-directory-path
      value: dependency-directory

    - name: report-file-path
      value: crda-report.json

    - name: crda-image
      value: quay.io/ksoneji/crda:maven
    
    - name: golang-image
      value: golang
    
    - name: total-vulnerabilities
      value: "3"

    - name: critical-vulnerabilities
      value: "0"
    
    - name: high-vulnerabilities
      value: "0"
    
    - name: medium-vulnerabilities
      value: "2"
    

    - name: low-vulnerabilities
      value: "3"